name: Daily Music Chart Collection

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 22 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v4

      # 2. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      # 3. Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager

      # 4. 스크립트 실행
      - name: Run and Commit Melon Korea Chart
        run: |
          python3 koreaMelonChart.py
          python3 koreaGenieChart.py
          python3 koreaBugsChart.py
          python3 koreaFloChart.py
          python3 koreaVibeChart.py
          git add korea/**/*.json
          git commit -m "Melon Korea Chart Updated - $(date +"%Y-%m-%d")" || echo "No changes to commit"

      # 6. 변경사항 푸시
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
